package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	reClass    = regexp.MustCompile(`^class\s+(\w+)`)
	reFunc     = regexp.MustCompile(`^def\s+(test_\w+)`)
	reMethod   = regexp.MustCompile(`^\s{4}def\s+(test_\w+)`)
	reIndentFn = regexp.MustCompile(`^(\s*)def\s+(test_\w+)`)
)

func extractTests(root string) ([]string, error) {
	var out []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasPrefix(info.Name(), "test_") || !strings.HasSuffix(path, ".py") {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		rel = filepath.ToSlash(rel)
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		class := ""
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			line := sc.Text()
			if m := reClass.FindStringSubmatch(line); m != nil {
				class = m[1]
				continue
			}
			if strings.HasPrefix(line, "def ") {
				class = ""
			}
			if m := reFunc.FindStringSubmatch(line); m != nil && strings.HasPrefix(line, "def ") {
				out = append(out, rel+"::"+m[1])
				continue
			}
			if class != "" {
				if m := reMethod.FindStringSubmatch(line); m != nil {
					out = append(out, rel+"::"+class+"."+m[1])
				}
			}
		}
		return sc.Err()
	})
	sort.Strings(out)
	return out, err
}

func copyFile(src, dst string) error {
	b, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, b, 0o644)
}

func classify(id string) (status, reason, goFile string) {
	switch {
	case strings.Contains(id, "test_numpy"), strings.Contains(id, "test_numpy_func"):
		return "skipped", "python-ecosystem:numpy", ""
	case strings.Contains(id, "test_umath"):
		return "skipped", "python-ecosystem:numpy-umath", ""
	case strings.Contains(id, "test_dask"):
		return "skipped", "python-ecosystem:dask", ""
	case strings.Contains(id, "test_matplotlib"):
		return "skipped", "python-ecosystem:matplotlib", ""
	case strings.Contains(id, "test_babel"):
		return "skipped", "python-ecosystem:babel", ""
	case strings.Contains(id, "test_measurement"):
		return "skipped", "python-ecosystem:uncertainties", ""
	case strings.Contains(id, "test_diskcache"):
		return "skipped", "python-ecosystem:diskcache", ""
	case strings.Contains(id, "test_application_registry"):
		return "skipped", "python-ecosystem:application-registry", ""
	case strings.Contains(id, "test_compat"):
		return "skipped", "python-ecosystem:compat", ""
	case strings.Contains(id, "test_non_int"):
		return "skipped", "python-numeric:decimal", ""
	case strings.Contains(id, "benchmarks/"):
		return "skipped", "python-ecosystem:pytest-benchmark", ""
	case strings.Contains(id, "test_testing.py"):
		return "skipped", "python-ecosystem:pytest-helpers", ""
	case strings.Contains(id, "pickle"):
		return "skipped", "python-ecosystem:pickle", ""
	case strings.Contains(id, "test_converters.py"):
		return "ported", "", "converters_test.go"
	case strings.Contains(id, "test_definitions.py"):
		return "ported", "", "definitions_test.go"
	case strings.Contains(id, "test_util.py"):
		return "ported", "", "util_test.go"
	case strings.Contains(id, "test_unit.py"):
		return "ported", "", "unit_test.go"
	case strings.Contains(id, "test_quantity.py"):
		return "ported", "", "quantity_test.go"
	case strings.Contains(id, "test_log_units.py"):
		return "ported", "", "log_units_test.go"
	case strings.Contains(id, "test_contexts.py"):
		return "ported", "", "contexts_test.go"
	case strings.Contains(id, "test_systems.py"):
		return "ported", "", "systems_test.go"
	case strings.Contains(id, "test_errors.py"):
		return "ported", "", "errors_test.go"
	case strings.Contains(id, "test_formatting.py"), strings.Contains(id, "test_formatter.py"):
		return "ported", "", "formatting_test.go"
	case strings.Contains(id, "test_issues.py"):
		return "ported", "", "issues_test.go"
	case strings.Contains(id, "test_infer_base_unit.py"):
		return "ported", "", "infer_eval_test.go"
	case strings.Contains(id, "test_pint_eval.py"):
		return "ported", "", "infer_eval_test.go"
	case strings.Contains(id, "test_pitheorem.py"):
		return "ported", "", "infer_eval_test.go"
	default:
		return "skipped", "not-applicable:unclassified", ""
	}
}

func writeInventory(path string, tests []string, sha string) error {
	var b strings.Builder
	b.WriteString("# Generated by tools/syncpint. Do not hand-edit test ids;\n")
	b.WriteString("# re-run syncpint after upgrading Pint.\n")
	fmt.Fprintf(&b, "pint_sha: %s\n", sha)
	b.WriteString("tests:\n")
	for _, id := range tests {
		st, reason, goFile := classify(id)
		fmt.Fprintf(&b, "  - id: %q\n", id)
		fmt.Fprintf(&b, "    status: %s\n", st)
		if reason != "" {
			fmt.Fprintf(&b, "    reason: %q\n", reason)
		}
		if goFile != "" {
			fmt.Fprintf(&b, "    go: %s\n", goFile)
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func parseInventoryIDs(path string) (map[string]struct{}, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	ids := map[string]struct{}{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "- id:") {
			v := strings.TrimSpace(strings.TrimPrefix(line, "- id:"))
			v = strings.Trim(v, `"'`)
			ids[v] = struct{}{}
		}
	}
	return ids, sc.Err()
}

func main() {
	pint := flag.String("pint", "", "path to a Pint checkout")
	flag.Parse()
	root, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			fmt.Fprintln(os.Stderr, "go.mod not found")
			os.Exit(1)
		}
		root = parent
	}

	pintRoot := *pint
	if pintRoot == "" {
		pintRoot = filepath.Join(filepath.Dir(root), "pint")
	}
	suite := filepath.Join(pintRoot, "pint", "testsuite")
	if _, err := os.Stat(suite); err != nil {
		fmt.Fprintf(os.Stderr, "Pint testsuite not found at %s (pass --pint)\n", suite)
		os.Exit(1)
	}

	shaB, _ := os.ReadFile(filepath.Join(pintRoot, ".git", "HEAD"))
	sha := strings.TrimSpace(string(shaB))
	if strings.HasPrefix(sha, "ref:") {
		ref := strings.TrimSpace(strings.TrimPrefix(sha, "ref:"))
		if b, err := os.ReadFile(filepath.Join(pintRoot, ".git", ref)); err == nil {
			sha = strings.TrimSpace(string(b))
		}
	}
	if len(sha) > 7 {
		sha = sha[:7]
	}

	if err := copyFile(filepath.Join(pintRoot, "pint", "default_en.txt"), filepath.Join(root, "defs", "default_en.txt")); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := copyFile(filepath.Join(pintRoot, "pint", "constants_en.txt"), filepath.Join(root, "defs", "constants_en.txt")); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	_ = os.WriteFile(filepath.Join(root, "PINT_SHA"), []byte(sha+"\n"), 0o644)

	tests, err := extractTests(suite)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	inv := filepath.Join(root, "testdata", "inventory.yml")
	old, _ := parseInventoryIDs(inv)
	if err := writeInventory(inv, tests, sha); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var added, removed []string
	now := map[string]struct{}{}
	for _, id := range tests {
		now[id] = struct{}{}
		if _, ok := old[id]; !ok && len(old) > 0 {
			added = append(added, id)
		}
	}
	for id := range old {
		if _, ok := now[id]; !ok {
			removed = append(removed, id)
		}
	}
	fmt.Printf("Pint SHA %s: %d tests in inventory\n", sha, len(tests))
	if len(added) > 0 {
		fmt.Printf("new tests (%d):\n", len(added))
		for _, id := range added {
			fmt.Println(" +", id)
		}
	}
	if len(removed) > 0 {
		fmt.Printf("removed tests (%d):\n", len(removed))
		for _, id := range removed {
			fmt.Println(" -", id)
		}
	}
}
